config/routes.rb
Ej6::Application.routes.draw do
  resources :salesreps

  resources :sales
  root 'sales#index' 

end

app/models/sale.rb
class Sale < ActiveRecord::Base
   belongs_to :salesrep
end

app/models/salesrep.rb
class Salesrep < ActiveRecord::Base
  has_many :sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:ammount, :company, :salesrep_id)
    end
end

app/controllers/salesreps_controller.rb
class SalesrepsController < ApplicationController
  before_action :set_salesrep, only: [:show, :edit, :update, :destroy]

  # GET /salesreps
  # GET /salesreps.json
  def index
    @salesreps = Salesrep.all
  end

  # GET /salesreps/1
  # GET /salesreps/1.json
  def show
  end

  # GET /salesreps/new
  def new
    @salesrep = Salesrep.new
  end

  # GET /salesreps/1/edit
  def edit
  end

  # POST /salesreps
  # POST /salesreps.json
  def create
    @salesrep = Salesrep.new(salesrep_params)

    respond_to do |format|
      if @salesrep.save
        format.html { redirect_to @salesrep, notice: 'Salesrep was successfully created.' }
        format.json { render action: 'show', status: :created, location: @salesrep }
      else
        format.html { render action: 'new' }
        format.json { render json: @salesrep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salesreps/1
  # PATCH/PUT /salesreps/1.json
  def update
    respond_to do |format|
      if @salesrep.update(salesrep_params)
        format.html { redirect_to @salesrep, notice: 'Salesrep was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @salesrep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salesreps/1
  # DELETE /salesreps/1.json
  def destroy
    @salesrep.destroy
    respond_to do |format|
      format.html { redirect_to salesreps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salesrep
      @salesrep = Salesrep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salesrep_params
      params.require(:salesrep).permit(:name, :lastname, :territory, :quota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/salesreps_helper.rb
module SalesrepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ej6</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ammount %><br>
    <%= f.text_field :ammount %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :salesrep_id %><br>
    <%= f.number_field :salesrep_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <thead>
    <tr>
      <th>Ammount</th>
      <th>Company</th>
      <th>Salesrep</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.ammount %></td>
        <td><%= sale.company %></td>
        <td><%= sale.salesrep.name %>  <%= sale.salesrep.lastname %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ammount:</strong>
  <%= @sale.ammount %>
</p>

<p>
  <strong>Company:</strong>
  <%= @sale.company %>
</p>

<p>
  <strong>Salesrep:</strong>
  <%= @sale.salesrep_id %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>

app/views/salesreps/_form.html.erb
<%= form_for(@salesrep) do |f| %>
  <% if @salesrep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salesrep.errors.count, "error") %> prohibited this salesrep from being saved:</h2>

      <ul>
      <% @salesrep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :territory %><br>
    <%= f.text_field :territory %>
  </div>
  <div class="field">
    <%= f.label :quota %><br>
    <%= f.text_field :quota %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salesreps/edit.html.erb
<h1>Editing salesrep</h1>

<%= render 'form' %>

<%= link_to 'Show', @salesrep %> |
<%= link_to 'Back', salesreps_path %>

app/views/salesreps/index.html.erb
<h1>Listing salesreps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Territory</th>
      <th>Quota</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @salesreps.each do |salesrep| %>
      <tr>
        <td><%= salesrep.name %></td>
        <td><%= salesrep.lastname %></td>
        <td><%= salesrep.territory %></td>
        <td><%= salesrep.quota %></td>
        <td><%= link_to 'Show', salesrep %></td>
        <td><%= link_to 'Edit', edit_salesrep_path(salesrep) %></td>
        <td><%= link_to 'Destroy', salesrep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salesrep', new_salesrep_path %>

app/views/salesreps/new.html.erb
<h1>New salesrep</h1>

<%= render 'form' %>

<%= link_to 'Back', salesreps_path %>

app/views/salesreps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @salesrep.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @salesrep.lastname %>
</p>

<p>
  <strong>Territory:</strong>
  <%= @salesrep.territory %>
</p>

<p>
  <strong>Quota:</strong>
  <%= @salesrep.quota %>
</p>

<%= link_to 'Edit', edit_salesrep_path(@salesrep) %> |
<%= link_to 'Back', salesreps_path %>